name: Web CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: emscripten/emsdk:3.1.72
      volumes:
        - ./:/src
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Compilation
        id: compilation
        run: |
          mkdir web
          em++ src/main.cpp -o web/index.html
      - name: Upload
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deployment
        id: deployment
        uses: actions/deploy-pages@v4
